### ISSUE TITLE
Working as a junior developer

### ISSUE THREAD

**Issue by zoras** [RubyNepal/rorh#1]
I would like a developer to give a presentation sharing his/her work experience and guide to newcomers.

Congratulations! You've acquired your first programming job! Now what? What's involved, and how do you work effectively when you don't know everything?

**Comment by bishisht** [comment]
can we make it remote presentation ?

**Comment by zoras** [comment]
@bishisht ya sure

**Comment by MadhuriShres** [comment]
I am interested in giving talk on this topic.

**Comment by zoras** [comment]
:+1: @MadhuriShres Go for it.

**Comment by MadhuriShres** [comment]
:bow:

**Comment by zoras** [comment]
This talk is scheduled for March meetup.
See details here: http://www.meetup.com/Nepal-Ruby-Users-Group/events/229508916/
