### ISSUE TITLE
Scaling CI with Docker @ Cloudfactory

### ISSUE THREAD

**Issue by kajisaap** [RubyNepal/rorh#12]
CloudFactory is an agile workforce company which provides an online work platform for data-intensive processes offering technology companies to add human-powered features to their software platforms. 
Currently it has presence in Nepal, Kenya, US and moving ahead on expansion to many more countries. With many premium clients like Expensify, Microsoft, Duolingo,ESPN, CloudFactory is rapidly growing in operations as well as reach. 
              
To match this new season of ours, we re-architected many of our core infrastructure component with all the bells and whistles of metric-driven auto-scaling and added rigorous monitoring. But before scaling infrastructure, we were tasked with scaling development workflow. This presentation is going to be about one aspect of our development workflow optimisation. Somebody with no prior knowledge of [Jenkins](https://en.wikipedia.org/wiki/Jenkins_(software)) and the concept behind [CI](https://en.wikipedia.org/wiki/Continuous_integration) will have no good time in this talk. I know [Docker](https://en.wikipedia.org/wiki/Docker_(software)) must have hit your ears unless you were living under the rocks for past 2 years. 

Hi, I am Kaji and I am DevOps. 

Does *100s of server, monitoring, automation, business critical application deployments, true engineering culture* **entice** you ?? 
I am taking in DevOps of any caliber. Please feel free to ping me if you are interested. See you all in the venue. Cheers !!

**Comment by zoras** [comment]
Looking forward to see how much CF has changed in a year :smile:

**Comment by zoras** [comment]
This talk will be presented on Sunday, Jan 10th, 2016. See more at:
http://www.meetup.com/Nepal-Ruby-Users-Group/events/226808320/

**Comment by sameergautam** [comment]
(y)

**Comment by gkunwar** [comment]
:+1:

**Comment by kajisaap** [comment]
Thank you everybody for showing up. Thank you also for the :+1: up guys although they didn't show up. 
Talk slides are [here] (https://bit.ly/scaling_ci_with_dockers)

**Reiterating again**
>Does 100s of server, monitoring, automation, business critical application deployments, true engineering culture entice you ?? 
I am taking in DevOps of any caliber. Please feel free to ping me if you are interested. **Cheers** !!

**Comment by josisusan** [comment]
:+1: :bow:
