### ISSUE TITLE
Api first design with RoR

### ISSUE THREAD

**Issue by BipinBhandari** [RubyNepal/rorh#13]
It would be nice if someone could present on designing great apis in RoR.
These videos could be a reference
https://www.youtube.com/watch?v=PUuYAksQWg4
https://www.youtube.com/watch?v=PUuYAksQWg4

**Comment by milap-neupane** [comment]
Can this be extended to API first design with ruby? We can have a look at other frameworks too.

**Comment by zoras** [comment]
@milap-neupane ya sure!

**Comment by zoras** [comment]
We did a meetup on this recently. 

You can watch the video and slides here:
https://rubynepal.org/meetup/?episode=18
