### ISSUE TITLE
Organizing CSS

### ISSUE THREAD

**Issue by sanjeevpraja** [RubyNepal/rorh#14]
Structuring css, and developing a style Guide that bring consistency in design for mid to large scale Web  application.

**Comment by sushil10018** [comment]
Hey, I believe that I can coverup this topic. Can you please pass me the details regarding the time of presentation, venue and the approximate number of participants?

**Comment by zoras** [comment]
Hi @sushil10018, @sanjeevpraja is going to present on this topic at Sunday's meetup.
See details here: http://www.meetup.com/Nepal-Ruby-Users-Group/events/229508916/

**Comment by sushil10018** [comment]
Oh ok, got it @zoras dai! :+1:
