### ISSUE TITLE
How to do TDD in real life?

### ISSUE THREAD

**Issue by zoras** [RubyNepal/rorh#2]
Can someone shed light on the illusive TDD practice in regards to real life scenario?

**Comment by gkunwar** [comment]
@zoras I'll give talk on this topic.

**Comment by zoras** [comment]
@gkunwar :+1: GoodLuck!

**Comment by zoras** [comment]
https://www.rubynepal.org/blog/2015/12/23/ruby-meetup-december-20-2015/
