### ISSUE TITLE
Fast Parallel Tests with Docker and Containers

### ISSUE THREAD

**Issue by RohitRox** [RubyNepal/rorh#24]
Docker is a new way to containerize services. The primary use so far has been for deploying services in a very thin container. I experimented with using it for Continuous Integration so that I could run our rails tests within a consistent environment and runs test in parallel in multiple containers, and then I realized that using docker provides excellent encapsulation to allow for parallelization of rails test suites.

**Comment by RohitRox** [comment]
@zoras Yeah, that's the gist of this issue request. Thanks for the link.

**Comment by ashishbista** [comment]
@zoras @RohitRox BTW, parallel testing will be a [native thing in Rails 6](https://github.com/rails/rails/pull/31900). [parallel_tests](https://github.com/grosser/parallel_tests) gem also does the same thing.

**Comment by zoras** [comment]
I've been using [Knapsack gem](http://docs.knapsackpro.com/ruby/knapsack) to evenly split tests between two docker containers on [CircleCI](http://docs.knapsackpro.com/ruby/knapsack#info-for-circleci-users)
<img width="822" alt="screen shot 2018-04-12 at 9 19 50 pm" src="https://user-images.githubusercontent.com/365783/39539031-598f55e4-4e5e-11e8-96da-baa527e697c9.png">

**Comment by ashishbista** [comment]
@zoras have you tried parallel_tests and knapsack together?

**Comment by zoras** [comment]
Not yet. But I don't think it matters much for CI server. It would be better approach to use parallel_tests in local machine and knapsack on CI.

**Comment by zoras** [comment]
Slides and other resources can be found here https://github.com/RubyNepal/rorh/wiki/RoR-Himalayan-Meetup-at-Kathmandu,-May-2018

See also:

- https://github.com/tmm1/test-queue
- https://github.com/grosser/parallel_tests
- https://github.com/Shopify/rails_parallel
