### ISSUE TITLE
Maintaining Coding Standards with RuboCop, Overcommit, Pronto and Gitlab CI

### ISSUE THREAD

**Issue by coolprobn** [RubyNepal/rorh#27]
## Abstract

When working with the team it's crucial to maintain coding standards and write the code that adheres to best practices. This can generally be achieved with code reviews. But code reviews is for fruitful and logical discussions and not for discussions related to using single or multi quote, leaving blank lines after each methods, separating different code, etc... This can easily be achieved if we use code analyzer like RuboCop which helps to configure rules which all members in the team can follow once finalized with discussion.

This can further be made effective with overcommit, a gem for managing git hooks. This makes sure that code with warning or errors from RuboCop is never committed to the git repo. And with CI like Gitlab CI, it can also be checked if someone bypassed RuboCop in their local machine assuring that code that is committed has followed the best practices followed by best developers all around the world.

## Speak or Suggest

- [x] Speak (Give a presentation session)
- [ ] Suggestion (Suggesting a topic eager to see/learn)

_NOTE_: I have never given a talk before

## Intended Audience

- [x] All
- [ ] Beginner
- [ ] Intermediate
- [ ] Advanced

## Talk Duration

- [ ] 5-10 minutes Lightning Talk
- [x] 20 minutes Talk
- [ ] 30 minutes Talk with Demo
- [ ] Others (specify)

## Bio / About the author

Hi 👋 
I am Prabin Poudel, Senior Ruby on Rails Engineer, Freelancer and CEO of [Truemark Technology](https://truemark.dev)

I have been working with Rails for past 4 years and involved in a lot of code reviews inside our organization. At Truemark we take coding standards and quality very seriously and we use tools mentioned above to maintain best practices in all our projects.

---

**Comment by josisusan** [comment]
Thanks Prabin, this would be an awesome topic for the meetup. Would like to know your availability for next weekends (ie 18th Dec)

**Comment by coolprobn** [comment]
@josisusan What will be the agenda for our meeting? I will have to make time.

**Comment by josisusan** [comment]
I thought you want to speak on the topic. No hurry, we can take time to organize meetup. @coolprobn

**Comment by coolprobn** [comment]
Yes, I want to speak on this.

I am extremely busy for some weeks and I haven't even prepared slides for presentation 😅

**Comment by zoras** [comment]
Hey @coolprobn, did you manage to carve out some time for the slides?

**Comment by jonathanclarke** [comment]
@coolprobn did you want to talk on this tomorrow night?

**Comment by coolprobn** [comment]
@jonathanclarke I was not able to allocate time to create Presentations for this talk. I have done that now and am ready to give the talk. Please let me know when the next talk is and how I should collaborate for you to review these slides.

**Comment by jonathanclarke** [comment]
@zoras can you follow up?

**Comment by zoras** [comment]
Hi @coolprobn, can you share the slides on slack with me? We can do the meetup on Jan 17 if it works for you?
