### ISSUE TITLE
DDD with Ruby

### ISSUE THREAD

**Issue by sandeshbodake** [RubyNepal/rorh#28]
## Abstract
A short description of your talk.

If you have ever worked on a successful RoR-based application, you have probably experienced firsthand the problems that grow, when you apply MVC/CRUD to more complex requirements. You might introduce some extra layers, like services, interactors and such. So in this talk, I’ll be speaking about how you can achieve this better and how the DDD approach helps me.

Points I’ll be covering in a talk:

- Why DDD approach?
- What is Hexagonal architecture?
- Sample DDD project structure walkthrough
- How DDD helps me to solve business problems?

## Speak or Suggest

- [x] Speak (Give a presentation session)
- [ ] Suggestion (Suggesting a topic eager to see/learn)

## Intended Audience

- [x] All
- [ ] Beginner
- [ ] Intermediate
- [ ] Advanced

## Talk Duration

- [ ] 5-10 minutes Lightning Talk
- [ ] 20 minutes Talk
- [x] 30 minutes Talk with Demo
- [ ] Others (specify)

## Bio / About the author
What should the audience know about you? Feel free to include links to your website or social media accounts.

Hello, My name is Sandesh from Pune (India). I have 4 years of experience building software with Ruby, Kotlin, and JavaScript, in the last couple of years I have crafted more than 10+ projects also I love to write blogs and open-source contributions.

## Notes

---
* Do ask others to upvote this talk if you think this should be the one to be selected for upcoming meetup.

**Comment by zoras** [comment]
Hello @sandeshbodake, thanks for showing interest to speak at RubyNepal meetup. Will you be ready to present next week? https://www.meetup.com/nepal-ruby-users-group/events/289640242/

**Comment by sandeshbodake** [comment]
Hello @zoras,

Sorry I missed your comment notification, but I can present this talk to next week
Also, could our share with me any communication channels like LinkedIn or Slack here  

Thanks

**Comment by zoras** [comment]
Sounds great @sandeshbodake. Please join RubyNepal slack channel from here [bit.ly/JoinRubyNepalSlack2](https://bit.ly/JoinRubyNepalSlack2)

**Comment by zoras** [comment]
This meetup talk was held on Dec 20. Thanks @sandeshbodake 👍 
https://github.com/RubyNepal/rubynepal.github.io/pull/793
