### ISSUE TITLE
The Single Responsibility Principle - SOLID Principles

### ISSUE THREAD

**Issue by anmolshah80** [RubyNepal/rorh#30]
## Abstract
Creating quality code throughout the development phase is a mission of any developer who wants to follow best practices in order to reduce code complexity, the coupling between classes and dissociate responsibilities. The very first principle of solid deals specifically with optimizing classes to ensure that the classes adhere to the single responsibility which is a much needed approach to maintain the growing code base and keep it testable.

## Speak or Suggest
- [x] Speak (Give a presentation session)
- [ ] Suggestion (Suggesting a topic eager to see/learn)

_NOTE_: I have never given a talk before so I'll be ready to give a talk in another month's session.

## Intended Audience
- [x] All
- [ ] Beginner
- [ ] Intermediate
- [ ] Advanced

## Talk Duration
- [ ] 5-10 minutes Lightning Talk
- [x] 20 minutes Talk
- [ ] 30 minutes Talk with Demo
- [ ] Others (specify)

## Bio / About the author
Hello there! I am Anmol Shah, an Associate Software Engineer at [Truemark Technology](https://www.truemark.dev/). I have been working with React and Rails for the past 6 months and have been involved in writing code that is maintainable and testable for the most part.

**Comment by zoras** [comment]
Thanks for the talk submission @anmolshah80.

We would be glad to hear your talk at RubyNepal meetup.

Our next meetup will be on March 14, can you please prepare a presentation targeting the date?

Looking forward to your talk 👍

**Comment by anmolshah80** [comment]
@zoras due to a bit of workload I have not fully being able to prepare for this presentation so I might have to shift to next month's session. I will surely be ready with the presentation by next month.

**Comment by zoras** [comment]
Thanks for the talk @anmolshah80 

The slides and video of the talk can be accessed from https://rubynepal.org/meetup/?episode=24
https://www.meetup.com/nepal-ruby-users-group/events/292297488/
