### ISSUE TITLE
The Open Closed Principle - SOLID Principles

### ISSUE THREAD

**Issue by AdilRT** [RubyNepal/rorh#31]
## Abstract

In most of the cases, the larger your application, the greater number of bugs is introduced. Sometimes while implementing a new functionality makes us feel scared of breaking other parts of the code, so to reduce these large modification on existing code while adding a functionality, we should follow the O of the SOLID Principle which is the Open Closed Principle. It tells us to write a block of code in such a way that it should not be massively modified while adding a new functionality related to it in the future.

## Speak or Suggest
- [x] Speak (Give a presentation session)
- [ ] Suggestion (Suggesting a topic eager to see/learn)

## Intended Audience
- [x] All
- [ ] Beginner
- [ ] Intermediate
- [ ] Advanced

## Talk Duration
- [ ] 5-10 minutes Lightning Talk
- [x] 20 minutes Talk
- [ ] 30 minutes Talk with Demo
- [ ] Others (specify)

## Bio / About the author
Hey! Im Aadil Tuladhar, working as a Software Engineer at Truemark Technology and its been just more than a year learning and working with Rails and i am loving it.

**Comment by zoras** [comment]
Hello Aadil, thanks for you interest in speaking at RubyNepal meetup. We can schedule this talk for May session. Please create a suitable presentation slide in the meantime.

**Comment by zoras** [comment]
FYI @AdilRT the talk is scheduled on meetup https://www.meetup.com/nepal-ruby-users-group/events/292974483/

**Comment by AdilRT** [comment]
Hello saroj dai, i will be very busy around the the 1st and the 2nd week of May so I would like to request to reschedule my talk for the month of June. Thank you.

**Comment by zoras** [comment]
Hi @AdilRT, FYI your talk is featured for the meetup scheduled on June 13 https://www.meetup.com/nepal-ruby-users-group/events/292974483/

**Comment by AdilRT** [comment]
okai dai.
