### ISSUE TITLE
Faster test suites and TDD.

### ISSUE THREAD

**Issue by xhagrg** [RubyNepal/rorh#4]
Test Driven Development is one of the best practices, at least for me. Having your tests do the testing rather than having to manually test all the scenarios is really helps one to manage his/her time more on important things. Collaboration also becomes much more easier, if working on a big team. 

That being said, with the addition of tests for the things you write, the test suite becomes very big over time. It takes hours just to run all the test suite, having to wait for it to finish before you sign it off becomes a hassle as it grows. 

Having some one talk about how we can achieve faster test suites and how we can improve TDD would be really great!.

**Comment by zoras** [comment]
See https://github.com/RubyNepal/rorh/issues/24#issuecomment-390397103
