### ISSUE TITLE
Docker and Rails whales?

### ISSUE THREAD

**Issue by zoras** [RubyNepal/rorh#5]
What is Docker, what are its advantages and how to run a rails application on docker?

**Comment by vayu-technology** [comment]
This sounds like an awesome talk, even 3 years later.  I was thinking of doing one on kubernetes + rails in a production environment.

**Comment by zoras** [comment]
See slides and videos from "Docker and Docker Compose for Developers" by @thapakazi https://github.com/RubyNepal/rorh/wiki/RoR-Himalayan-Meetup-at-Kathmandu,-January-2018
