### ISSUE TITLE
Meeting women and men developers in Asia

### ISSUE THREAD

**Issue by nivdul** [RubyNepal/rorh#8]
I am a french developer, especially in data processing and analysis.
I plan to travel to Nepal, Laos, Cambodia and Indonesia for fun but also to meet women and men in tech (developer, coder, entrepreneur...) and to understand the local ecosystem.

**Comment by zoras** [comment]
https://www.rubynepal.org/blog/2015/12/23/ruby-meetup-december-20-2015/
