### ISSUE TITLE
Performance Improvement of Rails Application

### ISSUE THREAD

**Issue by sadiksha** [RubyNepal/rorh#9]
Have you ever experienced a slow application and restarted your apache server or rails server on production mode? I have. Besides users, I also felt annoyed working with slow application. It is tedious to implement new feature or even fix bug with slow application. Recently I implemented few performance improvement techniques. The techniques improved both client and server side performances. I would like to share my knowledge on this meetup and get feedbacks on how you improved your application as well.

**Comment by zoras** [comment]
Old friend from Germany will pull-up many tricks
Goodluck :+1:

**Comment by zoras** [comment]
This talk will be presented on Sunday, Jan 10th, 2016. See more at:
http://www.meetup.com/Nepal-Ruby-Users-Group/events/226808320/

**Comment by neutrino** [comment]
:thumbsup:

**Comment by sadiksha** [comment]
Thanks Saroj looking forward to it! :)

**Comment by gkunwar** [comment]
:+1:

**Comment by RohitRox** [comment]
sure it's gonna be great :+1:
